// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG5eDvWScbGE2eFv7AlqlZw1oGZN0AYp8',
    appId: '1:215381309372:web:fbb5a559eadc73e4ec1db9',
    messagingSenderId: '215381309372',
    projectId: 'mozhi-lang',
    authDomain: 'mozhi-lang.firebaseapp.com',
    storageBucket: 'mozhi-lang.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUqXG6gmMDts5YJuQnyCrJJi1I32DJvXY',
    appId: '1:215381309372:android:2c0b509c2fd7ca93ec1db9',
    messagingSenderId: '215381309372',
    projectId: 'mozhi-lang',
    storageBucket: 'mozhi-lang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_UwbWWTXOXPOIkz5bE3FwEdEXq5HIyBs',
    appId: '1:215381309372:ios:993da99f0f508880ec1db9',
    messagingSenderId: '215381309372',
    projectId: 'mozhi-lang',
    storageBucket: 'mozhi-lang.firebasestorage.app',
    iosBundleId: 'com.example.languageLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_UwbWWTXOXPOIkz5bE3FwEdEXq5HIyBs',
    appId: '1:215381309372:ios:993da99f0f508880ec1db9',
    messagingSenderId: '215381309372',
    projectId: 'mozhi-lang',
    storageBucket: 'mozhi-lang.firebasestorage.app',
    iosBundleId: 'com.example.languageLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG5eDvWScbGE2eFv7AlqlZw1oGZN0AYp8',
    appId: '1:215381309372:web:22c6079e5b6d2d4eec1db9',
    messagingSenderId: '215381309372',
    projectId: 'mozhi-lang',
    authDomain: 'mozhi-lang.firebaseapp.com',
    storageBucket: 'mozhi-lang.firebasestorage.app',
  );
}
